### ISSUE TITLE
The Chinese character name is displayed as ???, How do you fix it?

### ISSUE THREAD

**Issue by ghnicole** [P0nk/Cosmic#142]
CHARSET: ISO-8859-1 allows you to enter Chinese in the game and display it, but the Chinese character name is displayed as????

**Comment by truongdatnhan** [comment]
I think it is the client, not the server side.

**Comment by ghnicole** [comment]
> I think it is the client, not the server side.

Thank you for your answer, which pointed me in the direction.

**Comment by ghnicole** [comment]
`    private enum Language {
        LANGUAGE_US("US-ASCII"),
        _LANGUAGE_ALL("UTF-8"),_
        LANGUAGE_PT_BR("ISO-8859-1"),
        LANGUAGE_THAI("TIS620"),
        LANGUAGE_KOREAN("MS949");

        private final String charset;`

In addition to adding these, what else needs to be changed

**Comment by ghnicole** [comment]
private enum Language {
        LANGUAGE_US("US-ASCII"),
      + LANGUAGE_ALL("UTF-8"),
        LANGUAGE_PT_BR("ISO-8859-1"),
        LANGUAGE_THAI("TIS620"),
        LANGUAGE_KOREAN("MS949");

        private final String charset;

In addition to adding these, what else needs to be changed

**Comment by YanjinTian** [comment]
你这头像我认出你来了，哈哈哈，没想到你英语比我强多了，我找时间帮你弄好！

**Comment by ghnicole** [comment]
这下好了, 有大神帮忙了.

**Comment by shotaro7906** [comment]
太强了 蹲一个大佬帮忙修复 QxQ

**Comment by WILDDONG125** [comment]
你好，想请教最终是如何解决了这个问题的。
我也正好碰到了这个问题，我在客户端已经解决了输入的问题，但是输出的时候，比如聊天输出仍然是"???"，以及中文角色也仍然无法创建。

**Comment by CODPHISH** [comment]
大神，这个仓库的源码问题多不，我想从0开始学习下

**Comment by P0nk** [comment]
I have fixed one issue with packet encoding in v0.3.3, could you please try and see if it works? I only have an english client, so I can't test it properly.

**Comment by WILDDONG125** [comment]
> I have fixed one issue with packet encoding in v0.3.3, could you please try and see if it works? I only have an english client, so I can't test it properly.

hi it’s Kicks on dc, i have tested it already and both client and server side could receive the message correctly 
![Uploading AFA4298E-D6C5-403A-A193-C9E2A8BA8EE0.jpeg…]()

**Comment by WILDDONG125** [comment]
> I have fixed one issue with packet encoding in v0.3.3, could you please try and see if it works? I only have an english client, so I can't test it properly.

hi it’s Kicks on dc, i have tested it already and both client and server side could receive the message correctly 
![1B7CCBA1-3D83-4919-8E6B-518FD6D2886F](https://user-images.githubusercontent.com/48898690/222587952-50cec88f-b90b-4a02-8684-14ee2c1534ef.jpeg)

**Comment by YanjinTian** [comment]
> I have fixed one issue with packet encoding in v0.3.3, could you please try and see if it works? I only have an english client, so I can't test it properly.


The methods in the "src/main/java/tools/StringUtil.java" must also be modified, in some cases.
