### ISSUE TITLE
Issue with Modifying Database

### ISSUE THREAD

**Issue by Blazing-Spirit** [P0nk/Cosmic#151]
I installed the server and client with no deviation from the setup.  However, when I use the admin account (or the database when my character is logged out to modify the GM level in the table), all mobs stop moving until I attack them.  Is this intentional or a bug?  Thank you!

**Comment by Blazing-Spirit** [comment]
> command "!unhide"

Thank you so much!

**Comment by tim78245** [comment]
You may also be interested in  setting `USE_AUTOHIDE_GM: false` in config.yaml

**Comment by Blazing-Spirit** [comment]
> You may also be interested in setting `USE_AUTOHIDE_GM: false` in config.yaml

That's actually exactly what I need, thanks so much!
