### ISSUE TITLE
Want to add a function to system out the Opcode

### ISSUE THREAD

**Issue by WILDDONG125** [P0nk/Cosmic#163]
Hi, just wonder where can I add the system out code to let it tell me the opcode. I know it was in MapleServerHandler.java of HeavenMS, but didn't find it in Cosmic.

**Comment by P0nk** [comment]
This doesn't really qualify as an issue, it's more of a question that could be asked in the discord server.

To answer your question, there are no println statements anywhere. Instead, things are logged using Slf4j Logger, which means the text is displayed in the console as well as being written to a log file. 
All packets are logged of you enable the setting in the config file: USE_DEBUG_SHOW_PACKET. This is disabled by default.

**Comment by WILDDONG125** [comment]
Ohh, sorry, make the question in wrong place. But thanks for your help!
