### ISSUE TITLE
Realize the problem of swiping money through negative value of items or props

### ISSUE THREAD

**Issue by lvwoniu** [P0nk/Cosmic#167]
The issue of negative swiping money requires fixing this issue by causing items or equipment to be swiped a lot of money with negative numbers.

**Comment by P0nk** [comment]
I don't understand what you're saying. Is it possible to drop negative amount of mesos?

**Comment by lvwoniu** [comment]
There has been a batch of negative NPCs hanging outside the gang, and the original NPCs have not yet determined whether the store has sold wood, screws, and other props, as well as scripts

**Comment by lvwoniu** [comment]
There has been a batch of gang external programs with negative numbers, NPC brush props, and the original NPC has not yet determined. Look at the wood, screws, and other props sold in the store, as well as the script

**Comment by lvwoniu** [comment]
There has been a batch of gang plug-in programs with negative numbers. The original NPC has not determined whether to brush props. If you look at the items and scripts sold in the store, such as wood, screws, etc., the failure to determine causes them to use the plug-in program to control parameters to reach a negative value and achieve gold coins

**Comment by lvwoniu** [comment]
There are a number of gangs using external negative NPC brush items, the original NPC did not decide you look at the shop sold wood, screws, etc. Use plugins to make items sell negative and get money

**Comment by WILDDONG125** [comment]
> I don't understand what you're saying. Is it possible to drop negative amount of mesos?

I know the issue, this happened when players use a cheat or hack to edit the value to negative number, e.g. -1, when they exchange item via the js or shop, let's say 10 leafs to 10 maplepoints for example, after the cheat or hack, system won't take the require item from them and reward them 10 maplepoints as well.
Many gangs use this method to destroy servers or disrupt the economic system. BTW I don't know how to fix it, lol.

**Comment by tim78245** [comment]
Can you name a specific one Cosmic needs to fix? They all should have been patched already.
https://github.com/P0nk/Cosmic/commit/f74dfbb46a1fa10dcfb7e2d0a5f71a7d1c28ae61
