### ISSUE TITLE
A question about Autoban distance calculation

### ISSUE THREAD

**Issue by kncxstudio** [P0nk/Cosmic#211]
https://github.com/P0nk/Cosmic/blob/f63f7e13d46aa324fc3a700ca8532e5ef567edd5/src/main/java/net/server/channel/handlers/AbstractDealDamageHandler.java#L196C1-L197C1

Is it necessary to calculate the square root of distanceSq here?

**Comment by P0nk** [comment]
I'm not really sure, maybe? `distanceSq` produces the euclidean distance which I assume is intended. The autoban system is certainly not perfect and I've had a few false positives myself.

**Comment by P0nk** [comment]
Please open a new issue if you find a concrete problem rather than an open question.
