### ISSUE TITLE
Disconnects to login on opening an NPC store (CosmicWZ_2024-07-17_v0.14.0)

### ISSUE THREAD

**Issue by TicTacTris** [P0nk/Cosmic#257]
**Describe the bug**
Opening an NPC store that sells potions disconnects to login screen when using .wz files from **_CosmicWZ_2024-07-17_v0.14.0_**
Reverting to .wz files from **_CosmicWZ_2024-07-17_v0.14.0_** stops the disconnects to login screen.

**To Reproduce**
1. Go to an NPC with a store.
2. Click on NPC to enter the store.
3. Disconnects to login screen.

**Expected behavior**
No disconnects should occur.

**Screenshots**
N/A

**Comment by P0nk** [comment]
What has likely happened is you forgot to run the SQL migration script provided in database/sql/migration, namely `v0.14.0.sql`. Please run it and try again. If you don't run the script, there will be invalid items in the shops causing the disconnection you are experiencing.

Please run it and get back if the problem still occurs.
