### ISSUE TITLE
Docker compose maplestory service doesn't wait for db health before starting

### ISSUE THREAD

**Issue by wejrox** [P0nk/Cosmic#26]
executing `docker-compose up` for the first time failed for me since maplestory started before the database had initialised everything. It was fine the second run, presumably since the `db` had set up all the tables and made itself available for connection. 

Unfortunately compose doesn't have the inbuilt ability to wait until a service has passed its health checks before starting another service; instead `depends_on` only waits until the container starts.

Potential solutions could be to use a `wait-for` instead to await db connectivity?

**Comment by P0nk** [comment]
It does wait for the db to start (hikari connection pool to be more specific). I configured the max wait time to 60 seconds through `INIT_CONNECTION_POOL_TIMEOUT` in `config.yaml`, which seemed reasonable, but it's possible I should increase it further.

**Comment by wejrox** [comment]
Ah I see now, yeah that might be for the best. That said, I wasn't running on a great machine. I believe it only needed another 10 seconds or so.

**Comment by P0nk** [comment]
Will increase the default wait time to 90 seconds in a future PR. Closing this once it's merged to master.
