### ISSUE TITLE
Mount in config.yaml to maplestory service

### ISSUE THREAD

**Issue by wejrox** [P0nk/Cosmic#29]
Currently the config is built with the jar, but mounting it in would make it easier to redeploy and test changes, since it shouldn't need a full rebuild to be applied.

**Comment by wejrox** [comment]
I've got this working at the moment, also changed the build to copy in only what's needed to run, and do so in stages that make it easier to re-build and use cached files, which should speed up testing. 

It should also be possible to mount the wz files on top too if required, which would reduce what needs to be copied down to the jar itself.

I'd still want to copy everything in however, since it allows the developer to run the image standalone easily.

Let me know if you want a PR for this.

**Comment by P0nk** [comment]
Yes, please submit a PR.
