### ISSUE TITLE
Custom NPC scripts don't override the default

### ISSUE THREAD

**Issue by wejrox** [P0nk/Cosmic#30]
If you create a custom NPC script, it isn't executed if the NPC already has a `D0` entry in the wz xml.

For example, Cody has the following XML:
```
  <imgdir name="9200000">
    <string name="name" value="Cody"/>
    <string name="func" value="Wizet Wizard"/>
    <string name="n0" value="Hey, care to help me out??"/>
    <string name="n1" value="I&apos;m telling you, I really AM from WIZET!"/>
    <string name="d0" value="What&apos;s going on? I&apos;m Cody, the head programmer of MapleStory~"/>
    <string name="d1" value="Thanks to your help, the party went bananas! Boy it was fun. anyway, hope you liked the stuff that I gave you. I&apos;ll see you around~"/>
  </imgdir>
```
I created a new npc file (`scripts/npc/9200000.js`) and gave it custom content, but it's never executed. It seems most if not all of the npcs that are already in the WZ xml files have been skipped over if they already have text. It makes sense, but it's difficult if you want to have an npc become a custom npc.

I think the scripts should take precedence if they exist, instead of being a fallback. I think `scipting.npc.NPCConversationManager` may be the place to do it, but I haven't dug far enough to say for sure. 

A side use-case for this is fixing incorrect wording that was on some of the NPCs in v83.

Thoughts?

P.s. I came across this issue when trying to debug why Cody wasn't registering as an npc when debug mode is enabled and I clicked him. Seems like there are multiple pathways to having a conversation with an npc, maybe something to refactor.

**Comment by P0nk** [comment]
Some NPC conversations are defined in the WZ files, and some through scripts, and I'm pretty sure this is decided in the client. Luckily the HeavenMS client (and by extension the Cosmic client since no changes have been made to it) has a custom feature that allows the server to dictate which NPCs are scriptable. Here's a lead: https://github.com/P0nk/Cosmic/blob/master/src/main/java/constants/game/ScriptableNPCConstants.java

**Comment by wejrox** [comment]
Awesome thanks, I'll look into it soon
