### ISSUE TITLE
Change rebirth support to allow a custom npc id to be used

### ISSUE THREAD

**Issue by wejrox** [P0nk/Cosmic#32]
Currently rebirths can be turned on but they'll only we usable if you can find `Wolf Spirit Ryko` (9010021). We couldn't find that npc anywhere that was listed in the xml files, so I modified the rebirth system to allow a specific NPC id to be passed in.

This feature seems pretty useful, so I think it should be added. 

Since npcs that already have their conversations present in the `wz` don't automatically use the `*.js` file present and any npc should be usable, the id of the rebirth npc being set should be added to the list of npcs that will always use the override, if rebirths are enabled.

**Comment by wejrox** [comment]
Closes #33, closes #30

**Comment by P0nk** [comment]
You searched poorly. Searching for all occurrences of "9010021" in /wz/Map.wz gave me these hits: 
100000205
101000005
102000005
103000009
140010110
140010111

ie. hall of fame maps.

**Comment by wejrox** [comment]
Apologies, I believe I've misrepresented what i mean. I had someone search in the maps defined in the xml files but they weren't able to visually confirm the npcs existence. It's possible that we just missed it of course.
