### ISSUE TITLE
Rebirth doesn't clear old job quests which prevents players from being the same job again

### ISSUE THREAD

**Issue by wejrox** [P0nk/Cosmic#34]
Second job quests for explorers use custom quest IDs for tracking the progress (letter, marbles, proof of hero). When rebirthing, these quests are still marked as completed for the player, which prevents them from getting past the letter phase.

The custom quest IDs are not `short`s either, although they need to be in order to send the packet to the client. 
In order to set up the rebirth to reset completed class-specific quests, the custom quests will need to have their id changed to be `< 32767` in order to be a `short`, and the rebirth system will need to be extended to forfeit those quests. Currently, no method exists on the maple character to do so.

- [ ] Change custom explorer second job quest ids to be shorts instead of ints
- [ ] Add a method to lazily delete/forfeit quests to the maple character
- [ ] Figure out the list of quests that need to be forfeited for each class and create a reference to them
- [ ] Extend `MapleCharacter::rebirth` to also forfeit any job-specific quests

**Comment by P0nk** [comment]
No longer relevant as rebirth system has been removed.
