### ISSUE TITLE
Code formatting is inconsistent

### ISSUE THREAD

**Issue by wejrox** [P0nk/Cosmic#38]
This one may be controversial, but I think the code style should be standardised and applied to the repo. Currently there's a mix of tabs and spaces everywhere, some different brace placement etc. 

Since intellij community has become pretty standard next to vscode, I think it would be worth having a standard code style committed to the repo for both editors, then it can be applied automatically on save for js and java files.

Currently I've gotten around the tabs issue by changing the tab display to 8 characters in my IDE, which makes it look a bit better, but it's inconsistent.

Thoughts?

**Comment by P0nk** [comment]
Agree that the formatting should be consistent throughout the code base. One thing holding me back has been that it ruins "git blame" somewhat. I use it quite extensively to view the most recent changes to lines, as a form of "documentation", or understand the reason for things.

**Comment by P0nk** [comment]
With that said, I plan to auto-reformat all files soon, in its own PR.

**Comment by P0nk** [comment]
Fixed
