### ISSUE TITLE
Area bosses are not killable

### ISSUE THREAD

**Issue by P0nk** [P0nk/Cosmic#84]
Snow Witch, Security Camera, Deet and Roi, Scholar Ghost and Shade should be killable and stop using the warp attack when the reactor on the map has been triggered.

**Comment by P0nk** [comment]
Need to figure out the correct mob debuff to apply.

**Comment by Arnuh** [comment]
155 with level 2
157 with level 1

155 is evade, does -990
157 is seal so it wont warp you to town
